<?php
defined('PROM') or exit("Access denied");


class Index_Controller extends Base{

    protected $text;
 protected function input(){
     parent::input(); // сначала выполнится весь код в родительском методе
     $this->home_page = TRUE;

     $this->title .= "Главная";
     $this->text = $this->ob_m->get_home_page();

     $this->keywords = $this->text['keywords'];
     $this->description = $this->text['description'];;
     //print_r($this->text);
 }
    protected function output()
    {

        $this->content = $this->render(VIEW.'content', array(
                                                   'text' => $this->text
        ));
      // echo $this->header;//сгенерировали шапку сайта
       // $this->content;
        $this->page = parent::output(); // TODO: Change the autogenerated stub
        return $this->page;
    }
}